import shlex

from paperext.config import CFG


def parse_curl():
    """Parse curl_tokens generated by the output of Firefox Copy as cURL
    https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_list/index.html#context-menu

    Returns the curl options (auth headers, cookies, ...) with the request URL
    stripped out. The URL is located by prefix rather than by position, since
    Firefox may emit it either first (``curl 'URL' -H ...``) or last
    (``curl -H ... 'URL'``); ``report.py`` supplies its own ``/report`` URL.
    """
    cmd, *tokens = shlex.split((CFG.dir.paperoni / "curl_tokens").read_text())

    assert cmd == "curl"

    curl_options = []
    url = None
    for token in tokens:
        if url is None and token.startswith(CFG.paperoni.url):
            url = token
            continue
        curl_options.append(token)

    assert url is not None, (
        f"No {CFG.paperoni.url} request URL found in "
        f"{CFG.dir.paperoni / 'curl_tokens'}"
    )

    return curl_options
